--
-- auto generated by {{ meta.proc.name }} v{{ meta.proc.version }}
--
-- created: {{ meta.timestamp }}
-- menu name: {{ module.menu.name }}
-- menu UUID: {{ module.menu.uuid }}
-- dist UUID: {{ module.menu.dist_uuid }}
-- module: {{ module.id }}
--
--
{% block code %}
{% endblock code %}
-- eof
