/*
 * auto generated by {{ header.proc.name }} v{{ header.proc.version }}
 *
 * created: {{ header.timestamp }}
 * implements: {{ header.menu }}
 * module: {{ header.module }}
 *
 */
{% block code %}
{% endblock code %}
/* eof */
