/*
 * auto generated by {{ meta.proc.name }} v{{ meta.proc.version }}
 *
 * created: {{ meta.timestamp }}
 * menu name: {{ module.menu.name }}
 * menu UUID: {{ module.menu.uuid }}
 * module: {{ module.id }}
 *
 */
{% block code %}
{% endblock code %}
/* eof */
